{% set version = "0.2.0" %}
{% set sha256 = "11bf85baf471a47bd8135b0ad550427bcf175df8d59bfbfc4c2614777294e49b" %}

package:
    name: traittypes
    version: {{ version }}

source:
    fn: traittypes-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/t/traittypes/traittypes-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python
        - traitlets >=4.2.2,<5.0

test:
    imports:
        - traittypes

about:
    home: https://github.com/jupyter-incubator/traittypes
    license: BSD 3-Clause
    summary: Trait types for NumPy, SciPy and friends
    license_file: LICENSE

extra:
    recipe-maintainers:
        - SylvainCorlay
        - jasongrout
        - maartenbreddels
        - vidartf
