travis:
  secure:
    BINSTAR_TOKEN: SM1R1t/9UXK3pq4S6C82fEjmE4KrSOFYIUdrjTQJoD8pZQHyPRl1qJkCKWZr7KbY5DmH+Tof/c5AQpMBnXJRx09SPQvModc+tBMZCLhWwZAKo6+nAPwLX20RDD83/0uvXu7xR9s6TomJP9nAGpVKQF4bJgsAXZregz4ZH5WYyWNIaLNJW3Tkm4+O1gWonazqTDvtnP2L9M3TTP4RQl6qI5kvj6T4xFVyvvrwAl8NzOPwhZ3Ui+eHI/YosuF1Z2rTepZIF+QMdqfsmDo8cXEwGUGZ9u9Te0kLvIo8iI/d8RkYgl95Dw/nbi9BxQc+L6qEEumFfbOdnk+Nv+dZXJ2Tnwz9bsQ5oxoCrsmp2kM/VbizWMtXeuQyPukiKs+pqGpO31mjl0j4RFEJ+Jru/4Uiu5WVbfQhiodm5G/36DhBf8BIl2MOFg+QMzqPDp6Bj1KCkYeFRTlxl82GULK55mtLUDEBV9oocgHYi5AKZ4ruLEtgewos6uAL6BcVrCquPBohgIGi8D0cAdI7davBN+KP5rTEH2EYbb7kVIrtN0GOnn3exEWUZe+RkgMnYGxVgjDdDKNVF7//VOkPL7RYMfaBOF2Ptm1K4n4VHPUuvfCL5kbpd1Yig6Hb2R21VpKplkaO65HQw/YItVz/zFeOxY4wTHWwJuj4urQPN0GkUC5RqD4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
