travis:
  secure:
    BINSTAR_TOKEN: Gk7iuwtyCfQfZ1WaLSEjt2LufJQb34E9QpqeORAvcGTzaQwREHP0YcCAxdZGEuGLA1IXqL3Xdrfy+0+3pOnyqz72YqQuyKW7Ot1WfDvZk5RkNd1emLN2JiYxLi+JnzUzA8a3E6U16fpWYd+WrxnmV+YZdEOWe3lMgXh+aEfKr6QM64MFqEFLWmnnG9YqEAotXgkhgn0DAMaTdq2vCCv3OQ6fzdJFlHkAck7GVO0Qa9lRb1EmAKW48yYnqArAEiYPjWo6+nVebGaxzFZA1QnWx6qce59YgkBSg0NsODAbq+b7petMoZFj+SJTkeKfiU8uQ6KPqObNcodnSEmf4jCEp/LTxqL4rxhgUwqrvWlDGtK6c8n8lwISEYn7Y9nNCUJu8MjikXKbXOh0JYeRDN3xO+NpxylnHHQF+jSh9nslTfM6o15HC+K5GSg2i6Qhv8WV2dhtWuIdf3lS17Uw1ZQZ/PIwcaWjNwrFbQSZ00rrqydqsX3OJDqqJ0PViGTX4vlgwAfEiHJo7qMtQx9pL2t4ZxAvnkyu4IfZlEcVxcUpiGBdi4qutZyPDhEqbbK78bFDSOOr1pVDiY2mchqKnKw9knhzIPqj2eRlMOgWdtgHSL3wEciQQUtNd9zo9y6f89itzWAy6cZG65mKs9Pd5tKa1HY5I8KXtuVP3MbTNbn1Fi8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
